# Here are the supporting characters
define placeholder = Character("???")
define tutorial = Character("Tutorial")
define char1 = Character("Dr. Megan")
define char2 = Character("Prof. Tondor")
define char3 = Character("Prof. Tondor (?)")
define char4 = Character("Officer")
define deer = Character("Deer")
define zombie = Character("Zombie", color="#FF0000")
define driver = Character("Driver")
define lee = Character("Lee")
define jason = Character("Jason")
define mom = Character("Mom") # Real name Betsheba
define dad = Character("Dad") # Real name David
define fabien = Character("Fabien")
define clover = Character("Clover", color="#37FCFF")
define everyone = Character("Everyone")
define villager = Character("Villager")
define uzi = Character("Uzi")
define ryan = Character("Ryan")
define jack = Character("Jack")
define alien = Character("Alien")
define zarktain = Character("Zarktain")
define othelia = Character("Othelia")
define kraglin = Character("Kraglin")
define zyphax = Character("Zyphax")
define larx = Character("Larx")
define cassidy = Character("Cassidy")
define spencer = Character("Spencer")
define partner = Character("[persistent.side_quests_1['Partner']]")

# Here are the main characters
define mc = Character("[persistent.name]", color="#FFFFFF")
define azure = Character("Azure", color="#37FCFF")
define terrence = Character("Terrence", color="#FF8800")
define exaqlyon = Character("Exaqlyon", color="#00FF00")
define serpent = Character("Serpent", color="#D2D200")
define brittany = Character("Br33t4nny", color="#9500FF")
define megan = Character("Megan")
define scorpio = Character("Scorpio")
define grex = Character("Grex")
define xeon = Character("X30N")
