# Here are the supporting characters
define placeholder = Character("???")
define tutorial = Character("Tutorial")
define char1 = Character("Dr. Megan")
define char2 = Character("Prof. Tondor")
define char3 = Character("Prof. Tondor (?)")
define char4 = Character("Officer")
define deer = Character("Deer")
define zombie = Character("Zombie", color="#FF0000")
define driver = Character("Driver")
define lee = Character("Lee")
define jason = Character("Jason")
define mom = Character("Mom")
define dad = Character("Dad")
define fabien = Character("Fabien")
define clover = Character("Clover", color="#37fcff")

# Here are the main characters
define mc = Character("[persistent.name]")
define azure = Character("Azure")
define terrence = Character("Terrence")
define exaqlyon = Character("Exaqlyon")
define serpent = Character("Serpent")
define brittany = Character("Br33t4nny")
